name: spec

on:
  push:

# pipeline to execute
jobs:
  schema:
    runs-on: ubuntu-latest

    steps:
    - name: print
      env:
        SHHH: ${{ secrets.TESTING }}
      run: |
        echo falafel
        echo "${{ secrets.TESTING }}"
        echo falafel123
        echo ${SHHH}
